import { db } from './firebase';
import { collection, doc, setDoc, deleteDoc, query, where, getDocs, writeBatch } from 'firebase/firestore';

export async function getBills(householdId) {
  const q = query(collection(db, 'Bills'), where("householdId", "==", householdId));
  const querySnapshot = await getDocs(q);
  return querySnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
}

export async function addBill(householdId, billData) {
  const newBillRef = doc(collection(db, 'Bills'));
  const newBill = {
    id: newBillRef.id,
    householdId,
    ...billData
  };
  await setDoc(newBillRef, newBill);
  return newBill;
}

export async function deleteBill(billId) {
  await deleteDoc(doc(db, 'Bills', billId));
}

export async function updateBill(billId, updates) {
  const billRef = doc(db, 'Bills', billId);
  await setDoc(billRef, updates, { merge: true });
}

export async function getTransactions(householdId, month, year) {
  // If month/year are provided, filter. Otherwise get all.
  if (month && year) {
    const q = query(
      collection(db, 'Transactions'), 
      where("householdId", "==", householdId),
      where("month", "==", month),
      where("year", "==", year)
    );
    const querySnapshot = await getDocs(q);
    return querySnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
  } else {
    // Return all transactions for the tab
    const q = query(
      collection(db, 'Transactions'), 
      where("householdId", "==", householdId)
    );
    const querySnapshot = await getDocs(q);
    return querySnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
  }
}

export async function saveTransaction(householdId, billId, transactionData) {
  // Retain support for manual clears via dashboard
  const transactionId = transactionData.id || `manual_${billId}_${transactionData.year}_${transactionData.month}`;
  const txRef = doc(db, 'Transactions', transactionId);
  const txObj = {
    id: transactionId,
    householdId,
    billId,
    ...transactionData
  };
  await setDoc(txRef, txObj, { merge: true });
  return txObj;
}

export async function saveBulkTransactions(transactions) {
  const batch = writeBatch(db);
  transactions.forEach(tx => {
    // tx should already have a stable ID generated by the frontend CSV ingest logic
    const txRef = doc(db, 'Transactions', tx.id);
    batch.set(txRef, tx, { merge: true });
  });
  await batch.commit();
}

export async function updateTransaction(transactionId, updates) {
  const txRef = doc(db, 'Transactions', transactionId);
  await setDoc(txRef, updates, { merge: true });
}

export async function deleteTransaction(transactionId) {
  await deleteDoc(doc(db, 'Transactions', transactionId));
}
